name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 16
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16.14
    - run: npm ci
    - run: npm run build --if-present
    - run: npx vercel --token ${VERCEL_TOKEN} --prod
      env: 
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

  Deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.14'
    # - name: Install npm dependencies
    #   run: npm ci
    # - name: Run build task
    #   run: npm run build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v4.1.8
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-rltgoDzvO --delete'
          SOURCE: ./* # 这是要复制到阿里云静态服务器的文件夹名称
          REMOTE_HOST: '101.43.108.86' # 你的阿里云公网地址
          REMOTE_USER: root # 阿里云登录后默认为 root 用户，并且所在文件夹为 root
          TARGET: /var/projects/my-site-server/ # 打包后的 dist 文件夹将放在 /root/node-server
          SCRIPT_BEFORE: |
            pm2 stop server
            pm2 delete server
            rm -rf /var/projects/my-site-server/
          SCRIPT_AFTER: |
            cd /var/projects/my-site-server/
            npm ci
            npm run build
            pm2 start --name server /var/projects/my-site-server/dist/main.js
          
          
